# Generated by Django 4.2.3 on 2023-12-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('visitor', 'visitor')], default='employee', max_length=20, null=True),
        ),
    ]
